name: 'Deploy Vue app to Github Pages'

branding:
  icon: 'activity'
  color: 'blue'

description: 'This Action will build the project and deploy it to Github Pages'

inputs:
  username:
    description: 'Your username'
    required: true
  reponame:
    description: 'Your reponame'
    required: true
  token:
    description: 'Your Github token'
    required: true
  gitbranch:
    description: 'Your git main branch'
    required: false
    default: 'origin'
  gitemail:
    description: 'Your git commit email'
    required: false
    default: 'CI@example.com'
  gitname:
    description: 'Your git commit name'
    required: false
    default: 'CI'
  gitmsg:
    description: 'Your git commit message'
    required: false
    default: 'deploy'
  cname:
    description: 'Your custom domain'
    required: false
    default: 'none'
  packagemanager:
    description: 'The used package manager'
    required: false
    default: 'npm'

runs:
  using: "composite"
  steps:
      - name: Build Vue
        run: |
              if [ "npm"  ==  ${{ inputs.packagemanager }} ]; then npm ci; npm run build; fi
              if [ "yarn" ==  ${{ inputs.packagemanager }} ]; then yarn install --frozen-lockfile; yarn build; fi
              if [ "pnpm" ==  ${{ inputs.packagemanager }} ]; then npm install -g pnpm; pnpm install --frozen-lockfile; pnpm run build; fi
              cd dist
              ln -s index.html 404.html
              if [ "none" !=  ${{ inputs.cname }} ]; then echo '${{ inputs.cname }}' > CNAME; fi
              git config --global user.email "${{ inputs.gitemail }}"
              git config --global user.name "${{ inputs.gitname }}"
              git init
              git add -A
              git commit -m '${{ inputs.gitmsg }}'
              git push -f https://${{ inputs.username }}:${{ inputs.token }}@github.com/${{ inputs.username }}/${{ inputs.reponame }}.git ${{ inputs.gitbranch }}:gh-pages
        shell: bash
